---
- hosts: hetzner-cloud
  become: yes
  user: root
  tasks:
    ## Install updates
    - name: Update
      yum: name=* state=latest

    ## Create SSH group
    - name: SSH group
      group:
        name: sshusers
        state: present

    ## Create SSH user
    - name: SSH user
      user:
        name: "{{ ssh_user_username }}"
        password: "{{ ssh_user_password | password_hash('sha512') }}"
        groups:
          - sshusers
          - sudo
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: "/home/{{ ssh_user_username }}"

    ## Set SSH user key
    - name: SSH user key
      authorized_key:
        user: "{{ ssh_user_username }}"
        state: present
        key: "{{ lookup('file', '{{ ssh_user_keyfile_path }}') }}"

    ## SSH Config
    - name: SSH Config update
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644

    ## Change root user password
    - name: Root password
      user:
        name: root
        password: "{{ root_password | password_hash('sha512') }}"

    ## SSH Port
    - name: Update SSH port in ssh config
      replace:
        path: /etc/ssh/sshd_config
        regexp: "<SSH_PORT_PLACEHOLDER>"
        replace: "{{ ssh_port }}"
    
