---
# tasks file for docker-init
- name: Install Docker and Docker Compose on CentOS
  hosts: all
  become: true
  tasks:
    - name: initial config
      import_task: initVMs.yml
    
    - name: setup docker
      import_task: setupDocker.yml


