---
# tasks file for docker-init
- name: Install Docker and Docker Compose on CentOS
  hosts: all
  gather_facts: true
  become: yes
  user: root
  tasks:
    - name: initial config
      import_tasks: ./initVMs.yml
      
- name: Install Docker and Docker Compose on CentOS
  hosts: all
  gather_facts: true
  become: yes
  user: docker
  tasks: 
    - name: setup docker
      import_tasks: setupDocker.yml

- name: setup swarm
  hosts: masters
  tasks:
    - name: setup swarm
      become_user: docker
      import_tasks: setupDockerSwarm.yml



- name: join Workers
  hosts: workers
  tasks:
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: System {{ groups["masters"][0] }} 
    - name: Fetch join token
      shell: rsync -e "ssh -i /home/docker/.ssh/id_rsa" docker@{{ groups["masters"][0] }}:/tmp/worker_join.sh /tmp/
      #add with items to loop on multiple workers even if not needed for the challenge for future reuse
    - name: Add Workers to the Swarm
      shell: bash /tmp/worker_join.sh
      tags: swarm



