- name: "Add Docker YUM Repository"
  yum_repository:
    name: "Docker"
    description: "Docker Repo"
    baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
    gpgcheck: "no"

- name: "Install Docker and Yum Utils"
  yum: 
    name: "{{ item }}"
    state: present
  with_items: 
    - yum-utils
    - yumlock
    - "docker-ce-{{ docker_version }}.ce-1.el7.centos"
    - "docker-ce-cli-{{ docker_version }}.ce-1.el7.centos"
    - containerd.io

- name: "Pin Docker Version"
  shell: "yumlock docker*"
    